#!/bin/bash

### SwayBar Configuration File

### Date
date=$(date +'🗓️ %a %d %b %Y  %H:%M')

### Battery
battery_capacity=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)
if [[ $battery_status = Charging ]] ; then
	battery_icon=$(echo "⚡🔋")
else
	battery_icon=$(echo "🔋")
fi

battery=$(echo "$battery_icon$battery_capacity%")

### Audio
audio_perc=$(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}')
audio_mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
if [[ $audio_mute = yes ]] ; then
        audio=$(echo "🔇")
else
        audio=$(echo "🔊$audio_perc%")
fi

mic=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')
if [[ $mic = yes ]] ; then
        mic_icon=$(echo "")
else
        mic_icon=$(echo "")
fi



### Network
ip=$(hostname -i)
if [[ $ip = 127.0.0.2 ]] ; then
        ip_status=$(echo "⚠️ Disconnected")
else
	ip_status=$(echo "🌐 $ip")
fi


### System
temp=$(sensors | grep "CPU" | awk '{print $2}')

bluetooth=$(bluetooth | awk '{print $3}')

#disk=$(df | grep "/dev/mapper/system" | awk '{print $5}')

#ram=$(free --si -h | grep "Mem" | awk '{print $3}')


echo "$mic_icon  $audio |  $bluetooth | $ip_status |🌡️$temp | $battery | $date |  $USER |"
