#!/bin/bash

# AUDIO
audio_perc=$(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}')
audio_mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
if [[ $audio_mute = yes ]] ; then
        audio=$(echo "🔇")
else
        audio=$(echo "🔊$audio_perc%")
fi

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	pactl set-sink-mute @DEFAULT_SINK@ toggle && pkill -RTMIN+8 i3blocks
fi

# MICROPHONE
mic_status=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')
if [[ $mic_status = yes ]] ; then
        mic=$(echo "")
else
        mic=$(echo "")
fi

if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  pactl set-source-mute @DEFAULT_SOURCE@ toggle && pkill -RTMIN+8 i3blocks
fi

# OUTPUT
echo "$mic  $audio" 
