#!/bin/bash

audio_perc=$(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}')
audio_mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
if [[ $audio_mute = yes ]] ; then
        audio=$(echo "🔇")
else
	if [[ $audio_perc -gt 100 ]]; then
		echo "🔊$audio_perc%" && echo "" && echo "#ff0000"
	else
		echo "🔊$audio_perc%" && echo "" && echo "#fffff"
	fi
fi

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	pactl set-sink-mute @DEFAULT_SINK@ toggle && pkill -RTMIN+8 i3blocks
fi

