#!/bin/bash

# Prendo informazioni dell'audio
AUDIO_PERC=$(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}')
AUDIO_MUTE=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

if [[ $AUDIO_MUTE = yes ]] ; then
	COLOR="#FF0000"
	ICON=""
else
	COLOR="#FFFFFF"
	if [[ $AUDIO_PERC -gt 100 ]]; then
		COLOR="#ff0000"
		ICON=""
    	elif [[ $AUDIO_PERC -gt 45 ]]; then
        	ICON=""
    	elif [[ $AUDIO_PERC -gt 0 ]]; then
        	ICON=""
    	else
        	ICON=""
    	fi
fi

# Output
echo "$ICON $AUDIO_PERC%" && echo "" && echo "$COLOR"

# Mouse click event
case $BLOCK_BUTTON in
    1) pactl set-sink-mute @DEFAULT_SINK@ toggle;;
esac


