#!/bin/bash

# Prendere informazioni sulla batteria
BAT="BAT0"
BAT_PERC=$(cat /sys/class/power_supply/$BAT/capacity)
BAT_STATUS=$(cat /sys/class/power_supply/$BAT/status)

# Controllo se la batteria è presente
if [[ -z "$BAT_PERC" ]] ; then
	echo ""
else
	# Controllo se la batteria è in carica
	if [[ $BAT_STATUS = Charging ]] ; then
        	COLOR="#FFFF00"
		CHARGE_ICON=" "
        else
        	if [[ ! $BAT_PERC -gt 30 ]] ; then
        		COLOR="#ff0000"
        	else
        		COLOR="#ffffff"
        	fi
	fi

        if [[ $BAT_PERC -gt 80 ]] ; then
        	BAT_ICON=""
        elif [[ $BAT_PERC -gt 60 ]] ; then
            	BAT_ICON="" 
        elif [[ $BAT_PERC -gt 40 ]] ; then
            	BAT_ICON="" 
        elif [[ $BAT_PERC -gt 20 ]] ; then
            	BAT_ICON=""
        else
            	BAT_ICON=""
        fi
        
        # Output
        echo "$CHARGE_ICON$BAT_ICON $BAT_PERC%" && echo "" && echo "$COLOR"
fi

