#!/bin/bash

battery_capacity=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)
if [[ $battery_status = Charging ]] ; then
        battery_icon=$(echo "⚡🔋")
else
        battery_icon=$(echo "🔋")
fi
echo "$battery_icon$battery_capacity%"
