#!/bin/bash

BLUETOOTH=$(bluetooth | awk '{print $3}')

if [[ $BLUETOOTH = off ]]; then
	COLOR="#ff0000"
fi

# Outuput
echo " $BLUETOOTH" && echo "" && echo "$COLOR"

# Mouse click event
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
        bluetooth toggle
fi

