#!/bin/bash

bluetooth=$(bluetooth | awk '{print $3}')

if [[ $bluetooth = on ]]; then
	echo " $bluetooth"
else
	echo " $bluetooth" && echo "" && echo "#ff0000"
fi


if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
        bluetooth toggle
fi
