#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Long;

# Default values
my $t_warn = $ENV{T_WARN} // 50;
my $t_crit = $ENV{T_CRIT} // 80;
my $cpu_usage = -1;
my $label = $ENV{LABEL} // "";
my $color_normal = "#FFFFFF";  # Bianco
my $color_warn = "#FFFFFF";    # Bianco
my $color_crit = "#FFFFFF";    # Bianco

sub help {
    print "Usage: cpu_usage [-w <warning>] [-c <critical>]\n";
    print "-w <percent>: warning threshold to become yellow\n";
    print "-c <percent>: critical threshold to become red\n";
    exit 0;
}

GetOptions("help|h" => \&help,
           "w=i"    => \$t_warn,
           "c=i"    => \$t_crit,
);

# Get CPU usage
$ENV{LC_ALL} = "en_US";  # If mpstat is not run under en_US locale, things may break, so make sure it is
open (MPSTAT, 'mpstat 1 1 |') or die;
while (<MPSTAT>) {
    if (/^.*\s+(\d+\.\d+)[\s\x00]?$/) {
        $cpu_usage = 100 - $1;  # 100% - %idle
        last;
    }
}
close(MPSTAT);

$cpu_usage eq -1 and die "Can't find CPU information";

# Print short_text, full_text
printf " ${label}%.0f%%\n", $cpu_usage;

# Print color (always white)
print "${color_normal}\n";

exit 0;

