#!/bin/bash

CPU_USAGE=$(top -bn 2 -d 1 | grep '^%Cpu' | tail -n 1 | awk '{print 100 - $8}')

COLOR="#FFFFFF"
if [[ CPU_USAGE -gt 80 ]] ; then
	COLOR="#FF0000"
fi

# OUTPUT
echo " $CPU_USAGE%" && echo "" && echo "$COLOR"

# Mouse click event
case $BLOCK_BUTTON in
	3)
		CPU_INFO=$(cat /proc/cpuinfo | grep "model name" | head -n 1 | awk -F: '{print $2}')
		notify-send "$CPU_INFO"
	;;
esac
