#!/bin/bash

CPU_USAGE=$(top -bn 2 -d 1 | grep '^%Cpu' | tail -n 1 | awk '{print 100 - $8}')

COLOR="#FFFFFF"
if [[ CPU_USAGE -gt 80 ]] ; then
	COLOR="#FF0000"
fi

# OUTPUT
echo " $CPU_USAGE%" && echo "" && echo "$COLOR"
