#!/bin/bash

TEMP=$(sensors | grep "Package id 0" | awk '{print $4}'| sed 's/^+//' | sed 's/°C//' | sed 's/\.0//')
COLOR="#FFFFFF"

if [[ $TEMP -gt 80 ]]; then
	COLOR="#FF0000"
	ICON=""
elif [[ $TEMP -gt 65 ]] ; then
	ICON=""
elif [[ $TEMP -gt 50 ]] ; then
    	ICON=""
else
	ICON=""
fi

# Output
echo "$ICON+$TEMP°C" && echo "" && echo "$COLOR"

# Mouse click event
case $BLOCK_BUTTON in
	1)	gnome-terminal -e htop
esac
