#!/bin/bash

TEMP=$(sensors | grep "Package id 0" | awk '{print $4}'| sed 's/^+//' | sed 's/°C//' | sed 's/\.0//')
COLOR="#FFFFFF"

if [[ $TEMP -gt 79 ]]; then
	COLOR="#FF0000"
	ICON="󰸁"
elif [[ $TEMP -gt 69 ]] ; then
	ICON="󰔏"
else
    	ICON="󱃃"
fi

# Output
echo "$ICON $TEMP°C" && echo "" && echo "$COLOR"

# Mouse click event
case $BLOCK_BUTTON in
	3)
		gnome-terminal --title="bpytop-terminal" -- bpytop
	;;
esac

