#!/bin/bash

TEMP=$(optirun nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader)
COLOR="#FFFFFF"

if [[ $TEMP -gt 79 ]]; then
	COLOR="#FF0000"
	ICON="󰸁"
elif [[ $TEMP -gt 69 ]] ; then
	ICON="󰔏"
else
    	ICON="󱃃"
fi

# Output
echo "$ICON $TEMP°C" && echo "" && echo "$COLOR"


