#!/bin/bash

TEMP=$(optirun nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader)
COLOR="#FFFFFF"

if [[ $TEMP -gt 80 ]]; then
	COLOR="#FF0000"
	ICON=""
elif [[ $TEMP -gt 65 ]] ; then
	ICON=""
elif [[ $TEMP -gt 50 ]] ; then
    	ICON=""
else
	ICON=""
fi

# Output
echo "$ICON+$TEMP°C" && echo "" && echo "$COLOR"


