#!/bin/bash

mic=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')
if [[ $mic = yes ]] ; then
        echo ""
else
        echo ""
fi

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  pactl set-source-mute @DEFAULT_SOURCE@ toggle && pkill -RTMIN+8 i3blocks
fi
