#!/bin/bash

MIC=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')
if [[ $MIC = no ]] ; then
        COLOR="#FFFFFF"
        ICON="󰍬"
else
	COLOR="#FF0000"
        ICON="󰍭"
fi

# Output
echo "$ICON" && echo "" && echo "$COLOR"

# Mouse click event
case $BLOCK_BUTTON in
    1) pactl set-source-mute @DEFAULT_SOURCE@ toggle && pkill -RTMIN+2 i3blocks;;
esac

