#!/bin/bash

ip=$(hostname -i | awk '{print $1}')
wifi=$(ip a | grep "state UP" | grep "wlan")
eth=$(ip a | grep "state UP" | grep "eth")
wwan=$(ip a | grep "state UP" | grep "wwan")

if [[ $ip = 127.0.0.2 ]] ; then
	COLOR=$(echo "#FF0000")
        echo " Disconnected" && echo "" && echo "$COLOR"
else
	COLOR=$(echo "#4AF626")
        if [[ ! -z "$eth" ]] ; then
		echo " $ip" && echo "" && echo "$COLOR"
	elif [[ ! -z "$wifi" ]] ; then
		echo " $ip" && echo "" && echo "$COLOR"
        elif [[ ! -z "$wwan" ]] ; then
		echo " $ip" && echo "" && echo "$COLOR"
	fi
fi

