#!/bin/bash

# Ottieni tutte le INTERFACES di rete attive
INTERFACES=$(ip -o link show | awk -F': ' '{print $2}')

# Colore verde
COLOR="#4AF626"

# Itera attraverso le INTERFACES
for INTERFACE in $INTERFACES; do
	
	# Ottieni l'indirizzo IP associato all'INTERFACE
	IP=$(ip addr show $INTERFACE | grep "inet " | awk '{print $2}' | cut -f1 -d/)
		
	# Controllo che l'OUTPUT sia presente
	if [[ ! -z $IP ]] ; then
		if [[ $INTERFACE = "wlan"* ]] ; then
			SSID=$(iw $INTERFACE info | grep "ssid" | awk '{print $2}')
			OUTPUT="$OUTPUT   $SSID"
		elif [[ $INTERFACE = "eth"* ]] ; then
			OUTPUT="$OUTPUT   $IP"
		elif [[ $INTERFACE = "wwan"* ]] ; then
			OUTPUT="$OUTPUT   $IP"
		elif [[ $INTERFACE = "tun"* ]] ; then
			OUTPUT="$OUTPUT   $IP"
		fi
	fi	
done	
if [[ -z "$OUTPUT" ]] ; then
	# Colore rosso
	COLOR="#FF0000"
        OUTPUT=" Disconnected"
fi

# Stampa l'OUTPUT
echo $OUTPUT && echo "" && echo "$COLOR"

# Mouse click event
case $BLOCK_BUTTON in
        1) iwgtk;;
esac
