#!/bin/bash

RAM=$(free -m | awk 'NR==2{printf "%d%%", int($3*100/$2)}' | sed 's/%//')

if [[ $RAM -gt 70 ]]; then
	echo " $RAM%" && echo "" && echo "#ff0000"
else
	echo " $RAM%" && echo "" && echo "#ffffff"
fi
