#!/bin/bash

# Ottieni l'indirizzo IP dell'interfaccia
INTERFACE="tun0"
IPV4=$(ip addr show $INTERFACE | grep "inet " | awk '{print $2}' | cut -f1 -d/)
IPV6=$(ip addr show $INTERFACE | grep "inet6 " | awk '{print $2}' | cut -f1 -d/)

if [[ -z $IPV4 ]] ; then
    exit 0
else
    COLOR="#4AF626"
    OUTPUT="󰖂"
fi

# Stampa l'OUTPUT
echo $OUTPUT && echo "" && echo "$COLOR"

# Mouse click event
case $BLOCK_BUTTON in
	3)
		notify-send "$INTERFACE:
$IPV4
$IPV6"
	;;
esac
