#!/bin/bash

# Ottieni l'indirizzo IP dell'interfaccia
INTERFACE="wlan0"
IPV4=$(ip addr show $INTERFACE 2>/dev/null | grep "inet " | awk '{print $2}' | cut -f1 -d/)
IPV6=$(ip addr show $INTERFACE 2>/dev/null | grep "inet6 " | awk '{print $2}' | cut -f1 -d/ | grep "fe80::")
SSID=$(iwconfig $INTERFACE 2>/dev/null | grep "ESSID" | awk -F'"' '{print $2}')

if [[ -z $IPV4 ]] ; then
    COLOR="#FF0000"
    OUTPUT="󰖪"
else
    COLOR="#4AF626"
    OUTPUT="󰖩"
fi

# Stampa l'OUTPUT
echo $OUTPUT && echo "" && echo "$COLOR"

# Mouse click event
case $BLOCK_BUTTON in
	3)
		notify-send "$INTERFACE:" "$SSID \n$IPV4 \n$IPV6"
	;;
esac
