#!/bin/bash

# Ottieni l'indirizzo IP dell'interfaccia
INTERFACE="wwan0"
IPV4=$(ip addr show $INTERFACE | grep "inet " | awk '{print $2}' | cut -f1 -d/)
IPV6=$(ip addr show $INTERFACE | grep "inet6 " | awk '{print $2}' | cut -f1 -d/)

if [[ -z $IPV4 ]] ; then
    COLOR="#FF0000"
    OUTPUT=""
else
    COLOR="#4AF626"
    OUTPUT=" $IPV4"
fi

# Stampa l'OUTPUT
echo $OUTPUT && echo "" && echo "$COLOR"

# Mouse click event
case $BLOCK_BUTTON in
	3)
		PUBLIC_IP=$(curl -s ipinfo.io/ip)
		notify-send "IP pubblico:  $PUBLIC_IP
IPv4 locale:  $IPV4
IPv6 locale:  $IPV6" 
	;;
esac
